// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrnsayzgykdgaofqerib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybnNheXpneWtkZ2FvZnFlcmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTkzODYsImV4cCI6MjA2NTAzNTM4Nn0.FykoEkQHgvAMdLtJ0rYkMF9LcZqcISBVDhPetSo7vaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);